title = "gitleaks config"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["AWS"]

[[rules]]
id = "github-pat"
description = "GitHub PAT"
regex = '''ghp_[a-zA-Z0-9]{36}'''
tags = ["GitHub"]

[[rules]]
id = "slack-webhook"
description = "Slack Webhook"
regex = '''https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[a-zA-Z0-9]+'''
tags = ["Slack"]
